//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.312
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenocide.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xenocide.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abandon Game ähnelt.
        /// </summary>
        internal static string BUTTON_ABANDON {
            get {
                return ResourceManager.GetString("BUTTON_ABANDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add project ähnelt.
        /// </summary>
        internal static string BUTTON_ADDPROJECT {
            get {
                return ResourceManager.GetString("BUTTON_ADDPROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Base Information ähnelt.
        /// </summary>
        internal static string BUTTON_BASE_INFORMATION {
            get {
                return ResourceManager.GetString("BUTTON_BASE_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bases ähnelt.
        /// </summary>
        internal static string BUTTON_BASES {
            get {
                return ResourceManager.GetString("BUTTON_BASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build Facilities ähnelt.
        /// </summary>
        internal static string BUTTON_BUILD_FACILITIES {
            get {
                return ResourceManager.GetString("BUTTON_BUILD_FACILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build New Base ähnelt.
        /// </summary>
        internal static string BUTTON_BUILD_NEW_BASE {
            get {
                return ResourceManager.GetString("BUTTON_BUILD_NEW_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buy ähnelt.
        /// </summary>
        internal static string BUTTON_BUY {
            get {
                return ResourceManager.GetString("BUTTON_BUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel selecting site for new base ähnelt.
        /// </summary>
        internal static string BUTTON_CANCEL_NEW_BASE {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL_NEW_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel project ähnelt.
        /// </summary>
        internal static string BUTTON_CANCELPROJECT {
            get {
                return ResourceManager.GetString("BUTTON_CANCELPROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string BUTTON_CLOSE {
            get {
                return ResourceManager.GetString("BUTTON_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string BUTTON_DELETE {
            get {
                return ResourceManager.GetString("BUTTON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Down ähnelt.
        /// </summary>
        internal static string BUTTON_DOWN {
            get {
                return ResourceManager.GetString("BUTTON_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Equip Craft ähnelt.
        /// </summary>
        internal static string BUTTON_EQUIP_CRAFT {
            get {
                return ResourceManager.GetString("BUTTON_EQUIP_CRAFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Funds ähnelt.
        /// </summary>
        internal static string BUTTON_FUNDS {
            get {
                return ResourceManager.GetString("BUTTON_FUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geoscape ähnelt.
        /// </summary>
        internal static string BUTTON_GEOSCAPE {
            get {
                return ResourceManager.GetString("BUTTON_GEOSCAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intercept ähnelt.
        /// </summary>
        internal static string BUTTON_INTERCEPT {
            get {
                return ResourceManager.GetString("BUTTON_INTERCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go to UFO&apos;s last known position ähnelt.
        /// </summary>
        internal static string BUTTON_LAST_POSITION {
            get {
                return ResourceManager.GetString("BUTTON_LAST_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left ähnelt.
        /// </summary>
        internal static string BUTTON_LEFT {
            get {
                return ResourceManager.GetString("BUTTON_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load ähnelt.
        /// </summary>
        internal static string BUTTON_LOAD {
            get {
                return ResourceManager.GetString("BUTTON_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Saved Game ähnelt.
        /// </summary>
        internal static string BUTTON_LOAD_SAVED_GAME {
            get {
                return ResourceManager.GetString("BUTTON_LOAD_SAVED_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manufacture ähnelt.
        /// </summary>
        internal static string BUTTON_MANUFACTURE {
            get {
                return ResourceManager.GetString("BUTTON_MANUFACTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manufacturing ähnelt.
        /// </summary>
        internal static string BUTTON_MANUFACTURING {
            get {
                return ResourceManager.GetString("BUTTON_MANUFACTURING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monthly Costs ähnelt.
        /// </summary>
        internal static string BUTTON_MONTHLY_COSTS {
            get {
                return ResourceManager.GetString("BUTTON_MONTHLY_COSTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Game ähnelt.
        /// </summary>
        internal static string BUTTON_NEW_GAME {
            get {
                return ResourceManager.GetString("BUTTON_NEW_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string BUTTON_NO {
            get {
                return ResourceManager.GetString("BUTTON_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        internal static string BUTTON_OPTIONS {
            get {
                return ResourceManager.GetString("BUTTON_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Patrol ähnelt.
        /// </summary>
        internal static string BUTTON_PATROL {
            get {
                return ResourceManager.GetString("BUTTON_PATROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quit ähnelt.
        /// </summary>
        internal static string BUTTON_QUIT {
            get {
                return ResourceManager.GetString("BUTTON_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Research ähnelt.
        /// </summary>
        internal static string BUTTON_RESEARCH {
            get {
                return ResourceManager.GetString("BUTTON_RESEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Return To Base ähnelt.
        /// </summary>
        internal static string BUTTON_RETURN_TO_BASE {
            get {
                return ResourceManager.GetString("BUTTON_RETURN_TO_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right ähnelt.
        /// </summary>
        internal static string BUTTON_RIGHT {
            get {
                return ResourceManager.GetString("BUTTON_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run Tests ähnelt.
        /// </summary>
        internal static string BUTTON_RUN_TESTS {
            get {
                return ResourceManager.GetString("BUTTON_RUN_TESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string BUTTON_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sell ähnelt.
        /// </summary>
        internal static string BUTTON_SELL {
            get {
                return ResourceManager.GetString("BUTTON_SELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soldiers ähnelt.
        /// </summary>
        internal static string BUTTON_SOLDIERS {
            get {
                return ResourceManager.GetString("BUTTON_SOLDIERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistics ähnelt.
        /// </summary>
        internal static string BUTTON_STATISTICS {
            get {
                return ResourceManager.GetString("BUTTON_STATISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stores ähnelt.
        /// </summary>
        internal static string BUTTON_STORES {
            get {
                return ResourceManager.GetString("BUTTON_STORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop ähnelt.
        /// </summary>
        internal static string BUTTON_TIME_STOP {
            get {
                return ResourceManager.GetString("BUTTON_TIME_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die x3600 ähnelt.
        /// </summary>
        internal static string BUTTON_TIME_X3600 {
            get {
                return ResourceManager.GetString("BUTTON_TIME_X3600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die x60 ähnelt.
        /// </summary>
        internal static string BUTTON_TIME_X60 {
            get {
                return ResourceManager.GetString("BUTTON_TIME_X60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die x86400 ähnelt.
        /// </summary>
        internal static string BUTTON_TIME_X86400 {
            get {
                return ResourceManager.GetString("BUTTON_TIME_X86400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transactions ähnelt.
        /// </summary>
        internal static string BUTTON_TRANSACTIONS {
            get {
                return ResourceManager.GetString("BUTTON_TRANSACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transfer ähnelt.
        /// </summary>
        internal static string BUTTON_TRANSFER {
            get {
                return ResourceManager.GetString("BUTTON_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transfers ähnelt.
        /// </summary>
        internal static string BUTTON_TRANSFERS {
            get {
                return ResourceManager.GetString("BUTTON_TRANSFERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UFO activity by Country ähnelt.
        /// </summary>
        internal static string BUTTON_UFO_BY_COUNTRY {
            get {
                return ResourceManager.GetString("BUTTON_UFO_BY_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UFO activity by Region ähnelt.
        /// </summary>
        internal static string BUTTON_UFO_BY_REGION {
            get {
                return ResourceManager.GetString("BUTTON_UFO_BY_REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Up ähnelt.
        /// </summary>
        internal static string BUTTON_UP {
            get {
                return ResourceManager.GetString("BUTTON_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-Corp activity by Country ähnelt.
        /// </summary>
        internal static string BUTTON_XCORP_BY_COUNTRY {
            get {
                return ResourceManager.GetString("BUTTON_XCORP_BY_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-Corp activity by Region ähnelt.
        /// </summary>
        internal static string BUTTON_XCORP_BY_REGION {
            get {
                return ResourceManager.GetString("BUTTON_XCORP_BY_REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-Net ähnelt.
        /// </summary>
        internal static string BUTTON_XNET {
            get {
                return ResourceManager.GetString("BUTTON_XNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string BUTTON_YES {
            get {
                return ResourceManager.GetString("BUTTON_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom In ähnelt.
        /// </summary>
        internal static string BUTTON_ZOOM_IN {
            get {
                return ResourceManager.GetString("BUTTON_ZOOM_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom Out ähnelt.
        /// </summary>
        internal static string BUTTON_ZOOM_OUT {
            get {
                return ResourceManager.GetString("BUTTON_ZOOM_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} days ähnelt.
        /// </summary>
        internal static string DLG_BUILDFACILITY_BUILD_TIME_FORMAT {
            get {
                return ResourceManager.GetString("DLG_BUILDFACILITY_BUILD_TIME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build Time ähnelt.
        /// </summary>
        internal static string DLG_BUILDFACILITY_COLUMN_BUILD_TIME {
            get {
                return ResourceManager.GetString("DLG_BUILDFACILITY_COLUMN_BUILD_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cost ähnelt.
        /// </summary>
        internal static string DLG_BUILDFACILITY_COLUMN_COST {
            get {
                return ResourceManager.GetString("DLG_BUILDFACILITY_COLUMN_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Facility ähnelt.
        /// </summary>
        internal static string DLG_BUILDFACILITY_COLUMN_FACILITY {
            get {
                return ResourceManager.GetString("DLG_BUILDFACILITY_COLUMN_FACILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maintenance ähnelt.
        /// </summary>
        internal static string DLG_BUILDFACILITY_COLUMN_MAINTENANCE {
            get {
                return ResourceManager.GetString("DLG_BUILDFACILITY_COLUMN_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Base Name ähnelt.
        /// </summary>
        internal static string DLG_NEWBASENAME {
            get {
                return ResourceManager.GetString("DLG_NEWBASENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Days left ähnelt.
        /// </summary>
        internal static string DLG_RESEARCH_COLUMN_DAYSLEFT {
            get {
                return ResourceManager.GetString("DLG_RESEARCH_COLUMN_DAYSLEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project ähnelt.
        /// </summary>
        internal static string DLG_RESEARCH_COLUMN_PROJECT {
            get {
                return ResourceManager.GetString("DLG_RESEARCH_COLUMN_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assigned Scientists ähnelt.
        /// </summary>
        internal static string DLG_RESEARCH_COLUMN_SCIENTISTS {
            get {
                return ResourceManager.GetString("DLG_RESEARCH_COLUMN_SCIENTISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No X-Net entry found for {0} ähnelt.
        /// </summary>
        internal static string EXCEPTION_NO_XNET_ENTRY_FOUND {
            get {
                return ResourceManager.GetString("EXCEPTION_NO_XNET_ENTRY_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry. Not implemented Yet! ähnelt.
        /// </summary>
        internal static string EXCEPTION_NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("EXCEPTION_NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UFOs don&apos;t have a homeBase ähnelt.
        /// </summary>
        internal static string EXCEPTION_UFOS_HAVE_NO_BASE {
            get {
                return ResourceManager.GetString("EXCEPTION_UFOS_HAVE_NO_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UFOs don&apos;t have fuel ähnelt.
        /// </summary>
        internal static string EXCEPTION_UFOS_LACK_FUEL {
            get {
                return ResourceManager.GetString("EXCEPTION_UFOS_LACK_FUEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attribute &quot;{0}&quot; not found in XML file ähnelt.
        /// </summary>
        internal static string EXCEPTION_XML_ATTRIBUTE_NOT_FOUND {
            get {
                return ResourceManager.GetString("EXCEPTION_XML_ATTRIBUTE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Barracks Facility ähnelt.
        /// </summary>
        internal static string FAC_BARRACKS_FACILITY {
            get {
                return ResourceManager.GetString("FAC_BARRACKS_FACILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Base Access Facility ähnelt.
        /// </summary>
        internal static string FAC_BASE_ACCESS_FACILITY {
            get {
                return ResourceManager.GetString("FAC_BASE_ACCESS_FACILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Engineering Facility ähnelt.
        /// </summary>
        internal static string FAC_ENGINEERING_FACILITY {
            get {
                return ResourceManager.GetString("FAC_ENGINEERING_FACILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GAIA Defense Array ähnelt.
        /// </summary>
        internal static string FAC_GAIA_DEFENSE_ARRAY {
            get {
                return ResourceManager.GetString("FAC_GAIA_DEFENSE_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gravity Shield ähnelt.
        /// </summary>
        internal static string FAC_GRAVITY_SHIELD_FACILITY {
            get {
                return ResourceManager.GetString("FAC_GRAVITY_SHIELD_FACILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Landing Pad ähnelt.
        /// </summary>
        internal static string FAC_LANDING_PAD {
            get {
                return ResourceManager.GetString("FAC_LANDING_PAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laser Defense Array ähnelt.
        /// </summary>
        internal static string FAC_LASER_DEFENSE_ARRAY {
            get {
                return ResourceManager.GetString("FAC_LASER_DEFENSE_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Long Range Neudar ähnelt.
        /// </summary>
        internal static string FAC_LONG_RANGE_NEUDAR {
            get {
                return ResourceManager.GetString("FAC_LONG_RANGE_NEUDAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missile Defense Array ähnelt.
        /// </summary>
        internal static string FAC_MISSILE_DEFENSE_ARRAY {
            get {
                return ResourceManager.GetString("FAC_MISSILE_DEFENSE_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neural Shielding Facility ähnelt.
        /// </summary>
        internal static string FAC_NEURAL_SHIELDING_FACILITY {
            get {
                return ResourceManager.GetString("FAC_NEURAL_SHIELDING_FACILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plasma Defense Array ähnelt.
        /// </summary>
        internal static string FAC_PLASMA_DEFENSE_ARRAY {
            get {
                return ResourceManager.GetString("FAC_PLASMA_DEFENSE_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Psionic Training Facility ähnelt.
        /// </summary>
        internal static string FAC_PSIONIC_TRAINING_FACILITY {
            get {
                return ResourceManager.GetString("FAC_PSIONIC_TRAINING_FACILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Research Facility ähnelt.
        /// </summary>
        internal static string FAC_RESEARCH_FACILITY {
            get {
                return ResourceManager.GetString("FAC_RESEARCH_FACILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short Range Neudar ähnelt.
        /// </summary>
        internal static string FAC_SHORT_RANGE_NEUDAR {
            get {
                return ResourceManager.GetString("FAC_SHORT_RANGE_NEUDAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storage Facility ähnelt.
        /// </summary>
        internal static string FAC_STORAGE_FACILITY {
            get {
                return ResourceManager.GetString("FAC_STORAGE_FACILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tachyon Emissions Detector ähnelt.
        /// </summary>
        internal static string FAC_TACHYON_EMISSIONS_DETECTOR {
            get {
                return ResourceManager.GetString("FAC_TACHYON_EMISSIONS_DETECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Xenomorph Holding Facility ähnelt.
        /// </summary>
        internal static string FAC_XENOMORPH_HOLDING_FACILITY {
            get {
                return ResourceManager.GetString("FAC_XENOMORPH_HOLDING_FACILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build Cost: {0} ähnelt.
        /// </summary>
        internal static string FACILITY_INFO_BUILD_COST {
            get {
                return ResourceManager.GetString("FACILITY_INFO_BUILD_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build Time (days): {0} ähnelt.
        /// </summary>
        internal static string FACILITY_INFO_BUILD_TIME {
            get {
                return ResourceManager.GetString("FACILITY_INFO_BUILD_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Capacity: {0} ähnelt.
        /// </summary>
        internal static string FACILITY_INFO_CAPACITY {
            get {
                return ResourceManager.GetString("FACILITY_INFO_CAPACITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accuracy: {0} ähnelt.
        /// </summary>
        internal static string FACILITY_INFO_DEFENSE_ACCURACY {
            get {
                return ResourceManager.GetString("FACILITY_INFO_DEFENSE_ACCURACY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Damage: {0} ähnelt.
        /// </summary>
        internal static string FACILITY_INFO_DEFENSE_DAMAGE {
            get {
                return ResourceManager.GetString("FACILITY_INFO_DEFENSE_DAMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Range (km): {0} ähnelt.
        /// </summary>
        internal static string FACILITY_INFO_DEFENSE_RANGE {
            get {
                return ResourceManager.GetString("FACILITY_INFO_DEFENSE_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maintenance Cost: {0} ähnelt.
        /// </summary>
        internal static string FACILITY_INFO_MAINTENANCE_COST {
            get {
                return ResourceManager.GetString("FACILITY_INFO_MAINTENANCE_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accuracy: {0} ähnelt.
        /// </summary>
        internal static string FACILITY_INFO_SCAN_ACCURACY {
            get {
                return ResourceManager.GetString("FACILITY_INFO_SCAN_ACCURACY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can determine UFO type, crew species and mission ähnelt.
        /// </summary>
        internal static string FACILITY_INFO_SCAN_DECODE {
            get {
                return ResourceManager.GetString("FACILITY_INFO_SCAN_DECODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Range (km): {0} ähnelt.
        /// </summary>
        internal static string FACILITY_INFO_SCAN_RANGE {
            get {
                return ResourceManager.GetString("FACILITY_INFO_SCAN_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scrap Value: {0} ähnelt.
        /// </summary>
        internal static string FACILITY_INFO_SCRAP_VALUE {
            get {
                return ResourceManager.GetString("FACILITY_INFO_SCRAP_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size: {0}m x {1}m ähnelt.
        /// </summary>
        internal static string FACILITY_INFO_SIZE {
            get {
                return ResourceManager.GetString("FACILITY_INFO_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is &quot;aeroscape&quot; screen, where an X-Corp craft attacks a UFO. However, as that&apos;s not implemented yet, click OK and code will pretend the attack was successful and the UFO crashed ähnelt.
        /// </summary>
        internal static string MSGBOX_AEROSCAPE_START {
            get {
                return ResourceManager.GetString("MSGBOX_AEROSCAPE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You already have a base called {0}.  You need to give the new base a different name. ähnelt.
        /// </summary>
        internal static string MSGBOX_BASE_NAMES_ARE_UNIQUE {
            get {
                return ResourceManager.GetString("MSGBOX_BASE_NAMES_ARE_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must give the base a name. ähnelt.
        /// </summary>
        internal static string MSGBOX_BASE_NEEDS_NAME {
            get {
                return ResourceManager.GetString("MSGBOX_BASE_NEEDS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is UFO crash recovery screen, where you get the chance to begin a battlescape mission. However, as that&apos;s not implemented yet, click OK and code will pretend the battlescape was successful ähnelt.
        /// </summary>
        internal static string MSGBOX_CRASH_RECOVERY {
            get {
                return ResourceManager.GetString("MSGBOX_CRASH_RECOVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Construction of {0} facility has been completed. ähnelt.
        /// </summary>
        internal static string MSGBOX_FINISHED_BUILDING_FACILITY {
            get {
                return ResourceManager.GetString("MSGBOX_FINISHED_BUILDING_FACILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aircraft {0} reports fuel low.  Returning to base. ähnelt.
        /// </summary>
        internal static string MSGBOX_FUEL_LOW {
            get {
                return ResourceManager.GetString("MSGBOX_FUEL_LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can&apos;t have more than eight bases. ähnelt.
        /// </summary>
        internal static string MSGBOX_MAX_EIGHT_BASES {
            get {
                return ResourceManager.GetString("MSGBOX_MAX_EIGHT_BASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You need to select a facility. ähnelt.
        /// </summary>
        internal static string MSGBOX_NO_FACILITY_SELECTED {
            get {
                return ResourceManager.GetString("MSGBOX_NO_FACILITY_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Research Project selected. ähnelt.
        /// </summary>
        internal static string MSGBOX_NO_RESEARCHTOPIC_SELECTED {
            get {
                return ResourceManager.GetString("MSGBOX_NO_RESEARCHTOPIC_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Scientists added ähnelt.
        /// </summary>
        internal static string MSGBOX_NO_SCIENTISTS_ADDED {
            get {
                return ResourceManager.GetString("MSGBOX_NO_SCIENTISTS_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bases can only have one {0} facility, and this base already has one. ähnelt.
        /// </summary>
        internal static string MSGBOX_ONLY_ONE_FACILITY_PER_BASE {
            get {
                return ResourceManager.GetString("MSGBOX_ONLY_ONE_FACILITY_PER_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have finished researching {0}. ähnelt.
        /// </summary>
        internal static string MSGBOX_RESEARCH_FINISHED {
            get {
                return ResourceManager.GetString("MSGBOX_RESEARCH_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interrogate Navigator ähnelt.
        /// </summary>
        internal static string RES_NAVIGATOR_INTERROGATION {
            get {
                return ResourceManager.GetString("RES_NAVIGATOR_INTERROGATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Building ähnelt.
        /// </summary>
        internal static string SCREEN_BASEINFO_COLUMN_BUILDING {
            get {
                return ResourceManager.GetString("SCREEN_BASEINFO_COLUMN_BUILDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idle ähnelt.
        /// </summary>
        internal static string SCREEN_BASEINFO_COLUMN_IDLE {
            get {
                return ResourceManager.GetString("SCREEN_BASEINFO_COLUMN_IDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In Use ähnelt.
        /// </summary>
        internal static string SCREEN_BASEINFO_COLUMN_IN_USE {
            get {
                return ResourceManager.GetString("SCREEN_BASEINFO_COLUMN_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type of Space ähnelt.
        /// </summary>
        internal static string SCREEN_BASEINFO_COLUMN_SPACE_TYPE {
            get {
                return ResourceManager.GetString("SCREEN_BASEINFO_COLUMN_SPACE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Staff Type ähnelt.
        /// </summary>
        internal static string SCREEN_BASEINFO_COLUMN_STAFF {
            get {
                return ResourceManager.GetString("SCREEN_BASEINFO_COLUMN_STAFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total ähnelt.
        /// </summary>
        internal static string SCREEN_BASEINFO_COLUMN_STAFF_TOTAL {
            get {
                return ResourceManager.GetString("SCREEN_BASEINFO_COLUMN_STAFF_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total ähnelt.
        /// </summary>
        internal static string SCREEN_BASEINFO_COLUMN_TOTAL {
            get {
                return ResourceManager.GetString("SCREEN_BASEINFO_COLUMN_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left click on location for first base. ähnelt.
        /// </summary>
        internal static string SCREEN_GEOSCAPE_FIRST_BASE {
            get {
                return ResourceManager.GetString("SCREEN_GEOSCAPE_FIRST_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save game with this name already exists. You need to delete it before you can create another with the same name. ähnelt.
        /// </summary>
        internal static string SCREEN_LOADSAVEGAME_DUPLICATE_FILENAME {
            get {
                return ResourceManager.GetString("SCREEN_LOADSAVEGAME_DUPLICATE_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Xeno Containment ähnelt.
        /// </summary>
        internal static string STORAGE_ALIENS_DISPLAY {
            get {
                return ResourceManager.GetString("STORAGE_ALIENS_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Landing Pads ähnelt.
        /// </summary>
        internal static string STORAGE_CRAFT_DISPLAY {
            get {
                return ResourceManager.GetString("STORAGE_CRAFT_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workshop ähnelt.
        /// </summary>
        internal static string STORAGE_ENGINEER_DISPLAY {
            get {
                return ResourceManager.GetString("STORAGE_ENGINEER_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General Storage ähnelt.
        /// </summary>
        internal static string STORAGE_GEAR_DISPLAY {
            get {
                return ResourceManager.GetString("STORAGE_GEAR_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bunks ähnelt.
        /// </summary>
        internal static string STORAGE_PERSONNEL_DISPLAY {
            get {
                return ResourceManager.GetString("STORAGE_PERSONNEL_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Psi Training Tanks ähnelt.
        /// </summary>
        internal static string STORAGE_PSI_TRAINING_DISPLAY {
            get {
                return ResourceManager.GetString("STORAGE_PSI_TRAINING_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laboratory ähnelt.
        /// </summary>
        internal static string STORAGE_SCIENTIST_DISPLAY {
            get {
                return ResourceManager.GetString("STORAGE_SCIENTIST_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scientists (Max. {0}): ähnelt.
        /// </summary>
        internal static string STR_SCIENTISTS_MAX {
            get {
                return ResourceManager.GetString("STR_SCIENTISTS_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can&apos;t build there, all facilities must have a fully constructed neighbour. ähnelt.
        /// </summary>
        internal static string XENOERROR_CELL_HAS_NO_NEIGHBOURS {
            get {
                return ResourceManager.GetString("XENOERROR_CELL_HAS_NO_NEIGHBOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can&apos;t destory this facility.  All facilities must have access to the lift. ähnelt.
        /// </summary>
        internal static string XENOERROR_DELETE_WILL_SPLIT_BASE {
            get {
                return ResourceManager.GetString("XENOERROR_DELETE_WILL_SPLIT_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can&apos;t destroy this facility, it is in use. ähnelt.
        /// </summary>
        internal static string XENOERROR_FACILITY_IS_IN_USE {
            get {
                return ResourceManager.GetString("XENOERROR_FACILITY_IS_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Everything&apos;s Fine ähnelt.
        /// </summary>
        internal static string XENOERROR_NONE {
            get {
                return ResourceManager.GetString("XENOERROR_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can&apos;t build there, that position is already in use. ähnelt.
        /// </summary>
        internal static string XENOERROR_POSITION_ALREADY_OCCUPIED {
            get {
                return ResourceManager.GetString("XENOERROR_POSITION_ALREADY_OCCUPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can&apos;t build there, not all the facility will be inside the base. ähnelt.
        /// </summary>
        internal static string XENOERROR_POSITION_NOT_IN_BASE {
            get {
                return ResourceManager.GetString("XENOERROR_POSITION_NOT_IN_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cost: {0} Area: {1} ähnelt.
        /// </summary>
        internal static string YESNOMSG_BUILD_BASE_HERE {
            get {
                return ResourceManager.GetString("YESNOMSG_BUILD_BASE_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dismantle {0}? ähnelt.
        /// </summary>
        internal static string YESNOMSG_DISMANTLE_FACILITY {
            get {
                return ResourceManager.GetString("YESNOMSG_DISMANTLE_FACILITY", resourceCulture);
            }
        }
    }
}
